name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: nocturlab/setup-vlang-action@v1
      with:
        v-version: master
    - name: Build boundstone
      run: v boundstone.v
    - name: Run boundstone
      run: ./boundstone
