name: CI

on: [push]

jobs:
  builde:
    name: Build using V ${{ matrix.v_version }}
    runs-on: 
      - ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        v_version: [master, latest]
    steps:
    - uses: actions/checkout@v1
    - uses: nocturlab/setup-vlang-action@v1
      with:
        v-version: ${{ matrix.v_version }}
    - name: Build boundstone
      run: v boundstone.v
    - name: Run boundstone
      run: ./boundstone
